language: python
cache:
  directories:
    - $HOME/.cache/pip
    - $HOME/.cache/pre-commit

python:
  - "3.6"

addons:
  postgresql: "9.6"
  apt:
    packages:
      - expect-dev # provides unbuffer utility

stages:
  - test

jobs:
  include:
    # Test separately: account_analytic_parent
    - stage: test
      env:
        - TESTS="1" ODOO_REPO="odoo/odoo" MAKEPOT="1" INCLUDE="account_analytic_parent"
    - stage: test
      env:
        - TESTS="1" ODOO_REPO="OCA/OCB" INCLUDE="account_analytic_parent"
    # Test separately: account_analytic_sequence
    - stage: test
      env:
        - TESTS=1 ODOO_REPO="odoo/odoo" MAKEPOT=1 INCLUDE="account_analytic_sequence"
    - stage: test
      env:
        - TESTS=1 ODOO_REPO="OCA/OCB" INCLUDE="account_analytic_sequence"
    # Test all other addons together
    - stage: test
      env:
        - TESTS=1 ODOO_REPO="odoo/odoo" MAKEPOT=1
          EXCLUDE="account_analytic_parent,account_analytic_sequence"
    - stage: test
      env:
        - TESTS=1 ODOO_REPO="OCA/OCB"
          EXCLUDE="account_analytic_parent,account_analytic_sequence"

env:
  global:
    - VERSION="14.0" TESTS="0" LINT_CHECK="0" MAKEPOT="0"
    - MQT_DEP=PIP

install:
  - git clone --depth=1 https://github.com/OCA/maintainer-quality-tools.git
    ${HOME}/maintainer-quality-tools
  - export PATH=${HOME}/maintainer-quality-tools/travis:${PATH}
  - travis_install_nightly

script:
  - travis_run_tests

after_success:
  - travis_after_tests_success
