##############################################################################
#    Copyright (c) 2021 brain-tec AG (http://www.braintec-group.com)
#    All Right Reserved
#
#    See LICENSE file for full licensing details.
##############################################################################

from odoo import api, models


class AccountAnalyticLine(models.Model):
    _inherit = 'account.analytic.line'

    @api.model
    def default_get(self, fields):
        defaults = super(AccountAnalyticLine, self).default_get(fields)

        if 'group_id' in fields:
            # Fixes the problem raised by the module "sale_stock", described below:
            # - From a sales order to be delivered we can reach all its deliveries via a smart button.
            # - The resulting view is generated by the method "action_view_delivery".
            # - This method defines the context variable "default_group_id", which refers to the procurement group
            # field in pickings.
            # - When validating one of the sales order's deliveries opened via the SO's smart button, an account
            # analytic line may be created.
            # - At this point in time, the context still contains the variable "default_group_id", which is a valid
            # default for us, but its value is not meant for us (which is likely to raise an error).
            # - Since the field "group_id" within "account.analytic.line" is a related field (to "account_id"),
            # it makes no sense to provide a default value.
            # - Consequently, it is safe to remove any default value for "group_id".
            del defaults['group_id']

        return defaults
